# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Bits Bytes and More
tagline:          'A Programming Blog'
description:      'A desperate high school programmers attempt at a blog'
url:              rgamberini.github.io
baseurl:          /
avatar:
  image:          /images/profile.png
  width:          285px
  height:         285px

author:
  name:           'Rudy Gamberini'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
